-- luacheck: no max line length
return {
  ["outcome.win"] = "Interrogation Successful",
  ["outcome.lose"] = "Interrogation Failed",
  ["outcome.episode8.win"] = "Cleared of charges. For now.",
  ["outcome.episode8.lose"] = "Suspended from your job as a result of Elias Hall's charges, you had to be removed from the task force.",
  ["outcome.episode9.win"] = "Now to bring these three together for questioning.",
  ["outcome.episode9.lose"] = "The lawyer comes in, shutting down your unlawful interrogation. You never get them in here again.",
  ["outcome.episode10.lose"] = "You breaching the agreements, Abraham Jamail ended all interviews. The Triumvirate slips through your fingers. ",

  ["episode9.select.tooltip.dennis"] = "Dennis Schmidt is a dentist, with no criminal record, flying alone. A quick background check revealed that he recently got engaged.",
  ["episode9.select.tooltip.valerie"] = "Valerie Arnette works for the exclusive travel agency that arranged all of the others' trips to Phnom Phen.",
  ["episode9.select.tooltip.anaba"] = "Anaba Lee is a reputed sociology and anthropology professor, scheduled to speak at a conference in Phnom Phen.",
  ["episode9.select.tooltip.reed"] = "Damascus Reed is a well-known entrepreneur and the driving force behind the recent tech business boom.",

  ["episode9.select.name.valerie"] = "Valerie Arnette",
  ["episode9.select.name.anaba"] = "Anaba Lee",
  ["episode9.select.name.dennis"] = "Dennis Schmidt",
  ["episode9.select.name.reed"] = "Damascus Reed",

  ["final_cutscene.select.label.good"] = "Book'm",
  ["final_cutscene.select.tooltip.good"] = "Time for the trial of the decade... and decades in jail.",

  ["final_cutscene.select.label.vigilante"] = "Summary executions",
  ["final_cutscene.select.tooltip.vigilante"] = "Proven to be scum, time to take them out for good - extrajudicially - whatever the personal consequences.",

  ["final_cutscene.select.label.marxist"] = "Release Lee",
  ["final_cutscene.select.tooltip.marxist"] = "Anaba's wing can help make a better world. Release her and detain Bennett and Reed.",

  ["final_cutscene.select.label.apocalyptic"] = "Release Bennett",
  ["final_cutscene.select.tooltip.apocalyptic"] = "The Colonel's wing can help make a better world. Release him and detain Lee and Reed.",

  ["final_cutscene.select.label.ancap"] = "Release Reed",
  ["final_cutscene.select.tooltip.ancap"] = "Reed's wing can help make a better world. Release him and detain Lee and Bennett.",

  ["final_cutscene.select.title"] = "You got 'em",
  ["final_cutscene.select.select_more"] = "What now?",
  ["final_cutscene.select.confirm"] = "Final Verdict",

  ["lore_card.jen.name"] = "Jennifer Reyes",
  ["lore_card.jen.good"] = "Jennifer Reyes quit the force a few years after the completion of the 'Triumvirate Trial'. Citing burnout and a lack of alignment with Police Department values, she retired and maintains a practice as a therapist.\n\nMordecai Fischer was her husband's best man at the wedding.",
  ["lore_card.jen.vigilante"] = "Jennifer Reyes succeeded Lucas Anderson as the Chief of Police after the fallout from the \"Triumvirate Executions\" scandal. Committed to restoring ethics to the department, she met fierce resistance from a police force committed to ending crime at any cost.\n\nShe ultimately retired from the post after receiving major life-threatening wounds in the line of duty.",
  ["lore_card.jen.marxist"] = "Jennifer Reyes campaigned powerfully to see Anaba Lee prosecuted. As her preoccupation with Lee and the case grew into obsession, she was removed from the police force.\n\nShe was later murdered in gunfire exchanges with Liberation Front followers.",
  ["lore_card.jen.ancap"] = "Jennifer Reyes quit the force after serving as the new Chief of Police for a few years.\n\nShe was a cofounder of the AEEAII, the Association for the Ethical Education of Artificially Intelligent Individuals.",
  ["lore_card.jen.apocalyptic"] = "Jennifer Reyes campaigned powerfully to see James Bennet prosecuted. As her preoccupation with Bennet and the case grew into obsession, she was removed from the police force.\n\nShe was murdered in gunfire exchanges with Liberation Front followers, weeks before the Last Fall.",

  ["lore_card.mordecai.name"] = "Mordecai Fischer",
  ["lore_card.mordecai.good"] = "Mordecai Fischer never moved up from his position on the force, nor pursued such ambitions. As a father, he focused on his emerging golf hobby and gained significant weight.\n\nHe remembers the Lead Detective fondly and often quotes their words of wisdom to his kids.",
  ["lore_card.mordecai.vigilante"] = "Mordecai Fischer never moved up from his position on the force, nor pursued major career ambitions. He retired from the police force after Chief Reyes's near-death incident.\n\nHe became a Police Academy instructor later in life, teaching the Investigative Interview and Interrogation Techniques course.",
  ["lore_card.mordecai.marxist"] = "Mordecai Fischer never moved up from his position on the force, nor pursued major career ambitions.\n\nHe became a People's Warden later in life, educating youth in matters of public safety.",
  ["lore_card.mordecai.ancap"] = "Mordecai Fischer never moved up from his position on the force, nor pursued major career ambitions.\n\nHe took on work as a Virtual Reality Security Enforcer and streamer later in life, gaining wide recognition and following under the FishyOfficer moniker.",
  ["lore_card.mordecai.apocalyptic"] = "Mordecai Fischer never moved up from his position on the force, nor pursued such ambitions.\n\nAfter the Last Fall, he founded and led Central Alpha, the Clan running the safest secure compound for many miles around, a lawful hub for free trade.",

  ["lore_card.tab.name"] = "Tab Thompson",
  ["lore_card.tab.good"] = "Tab Thompson followed a strong focused career as an officer and analyst. In their later years, they led the newly organised \"Algorithmic Crime Prevention\" pilot project.\n\nThey continued to keep in touch with those willing to subscribe to their weekly email update stream.",
  ["lore_card.tab.vigilante"] = "Tab Thompson resigned from the police force after the shock of the \"Triumvirate Executions\" and became a private contractor for private security companies.\n\nLater in life, they disappeared from all public records and never showed up with an official or digital footprint again.",
  ["lore_card.tab.marxist"] = "Tab Thompson followed a strong focused career as an officer and analyst.\n\nThey continued to keep in touch with those willing to subscribe to their weekly email update stream, until the Internet Segmentation Act was passed and such correspondence became disallowed.",
  ["lore_card.tab.ancap"] = "Tab Thompson resigned from the police force a few years later to be hired as a top executive for a major private security.\n\nLater in life, they disappeared from all public records and never showed up with an official or digital footprint again.",
  ["lore_card.tab.apocalyptic"] = "Tab Thompson followed a strong focused career as an officer and analyst.\n\nThey were not heard from again after the Last Fall took place.",

  ["lore_card.joseph.name"] = "Joseph Ward",
  ["lore_card.joseph.good"] = "Joseph Ward published a moderately successful semi-biographical trilogy of novels about fighting the forces of terrorism over multiple generations, spanning from the interwar period into a cyberpunk future.\n\nThe character corresponding to your generation is depicted as well-meaning but over-reliant on procedure.",
  ["lore_card.joseph.vigilante"] = "Joseph Ward published a moderately successful semi-biographical trilogy of novels about fighting the forces of terrorism over multiple generations, spanning from the past into a cyberpunk future.\n\nThe character corresponding to your generation is depicted as an ruthless but admirable anti-hero.",
  ["lore_card.joseph.marxist"] = "Joseph Ward published a moderately successful semi-biographical trilogy of novels about fighting the forces of terrorism over multiple generations, spanning from the interwar period into a cyberpunk future. The series was later banned.\n\nThe character corresponding to your generation is depicted as a weak-minded manipulated traitor.",
  ["lore_card.joseph.ancap"] = "Joseph Ward published a moderately successful semi-biographical trilogy of novels about fighting the forces of terrorism over multiple generations, spanning from the interwar period into a cyberpunk future. The series was adapted to holovid two decades later.\n\nThe character corresponding to your generation is depicted as a corrupted traitor.",
  ["lore_card.joseph.apocalyptic"] = "Joseph Ward published a moderately successful semi-biographical trilogy of novels about fighting the forces of terrorism over multiple generations, spanning from the interwar period into a cyberpunk future. Most copies were later burned for heat after the Last Fall.\n\nThe character corresponding to your generation is depicted as a sociopathic nihilist traitor.",

  ["lore_card.chief.name"] = "Chief Anderson",
  ["lore_card.chief.good"] = "Chief Anderson was hailed as a hero and went on to run the state-level Department of Public Safety a few years later.\n\nHe recommended the Lead Detective as his successor to lead the STPD.",
  ["lore_card.chief.vigilante"] = "Chief Anderson presented his resignation after being the direct superior of the rogue Lead Detective.\n\nHe moved to a small town in another state with his family, where he served as a patrol officer.",
  ["lore_card.chief.marxist"] = "Chief Anderson continued to lead the STPD until his resignation several years later after the murder of Jennifer Reyes.\n\nHe became a grandparent eight times.",
  ["lore_card.chief.ancap"] = "Chief Anderson massed all of police force's available resources to see Damascus Reed prosecuted. It soon cost him his position.\n\nAfter a messy divorce, he made ends meet later in life working as a mall guard.",
  ["lore_card.chief.apocalyptic"] = "Chief Anderson attempted but failed to combat the plots of James Bennet's Liberation Front.\n\nAfter the Last Fall, he became Clan Boss Fischer's right hand man in Central Alpha.",

  ["lore_card.james.name"] = "James Bennet",
  ["lore_card.james.apocalyptic"] = "James Bennet went on to take the Liberation Front to new heights.\n\nIncreasingly massive attacks took place, culminating with the the catastrophic events of the Last Fall.",

  ["lore_card.anaba.name"] = "Anaba Lee",
  ["lore_card.anaba.marxist"] = "Anaba Lee went on to take the Liberation Front to new heights, with representatives soon in politics and in every section of society.\n\nWhether or not the majority agreed with the Front, the landscape of ideas shifted and made for a new kind of society in coming decades.",

  ["lore_card.reed.name"] = "Damascus Reed",
  ["lore_card.reed.ancap"] = "Damascus Reed went on to take the Liberation Front to new heights, with representatives soon in politics and in every section of society.\n\nWhether or not the majority agreed with the Front, the landscape of ideas shifted and made for a new kind of society in coming decades.",

  ["lore_card.tristan.name"] = "Tristan Miller",
  ["lore_card.tristan.good"] = "Tristan Miller became mayor himself sixteen years later.",
  ["lore_card.tristan.vigilante"] = "Tristan Miller met the peak of his career when he lead the campaign of a major presidential candidate.\n\nTristan's candidate lost the election.",
  ["lore_card.tristan.marxist"] = "Tristan Miller was unable to ever hold significant political office, opponents always pointing to his privileged background.",
  ["lore_card.tristan.ancap"] = "Tristan Miller had a major mid-life crisis after the end of Mayor Patel's terms, switching to a career as a male model.",
  ["lore_card.tristan.apocalyptic"] = "Tristan Miller left to one of the safer continents with his wealthy family after the Last Fall.",

  ["lore_card.eddie.name"] = "Eddie Walker",
  ["lore_card.eddie.good"] = "Eddie Walker later in life left the journalism career to become Tristan Miller's campaign manager and spokesperson.",
  ["lore_card.eddie.vigilante"] = "Eddie Walker won multiple awards for his investigative pieces detailing police abuse and their cover-ups.",
  ["lore_card.eddie.marxist"] = "Eddie Walker became an international correspondent for a major national publication and soon after moved away to Hong Kong.",
  ["lore_card.eddie.ancap"] = "Eddie Walker won multiple awards for his investigative pieces detailing abusive corporate practices and market manipulation.",
  ["lore_card.eddie.apocalyptic"] = "Eddie Walker became an information broker after the Last Fall.\n\nOne of his most prized pieces of intel to sell was the current location of the Lead Detective that released James Bennet.",


  ["cutscene.t1"] = "The news is spreading through\nthe ranks of the Liberation Front.",
  ["cutscene.t2"] = "They were everywhere.",

  ["character_selection.confirm"] = "Confirm",
  ["character_selection.select_more"] = "Select ${count} more",
  ["character_selection.prompt"] = "Who should Morty bring in? We can only get a hold of two of them.",
  ["character_selection.prompt_confirm"] = "Good. I'll inform him.",

  ["missions.report_elias.title"] = "Report Elias Hall",
  ["missions.report_elias.description"] = "Formulate an extensive internal complaint to document the abusive behavior Elias Hall exhibited while questioning you.",
  ["missions.report_elias.success"] = "The grave aspects indicated in the report will be urgently investigated.",
  ["missions.report_elias.fail"] = "The report was apparently qualified as a trivial complaint after an initial review and may take months or years to be fully processed.",

  ["missions.denounce_elias.title"] = "Denounce Elias Hall",
  ["missions.denounce_elias.description"] = "Denounce to the press Elias Hall's actions exhibited while questioning you.",
  ["missions.denounce_elias.success"] = "The press is preparing the story for a front-page feature. The Chief, however, is livid that you took this story public before an internal investigation.",
  ["missions.denounce_elias.fail"] = "The press did not seem to treat the reported actions as an important enough. The Chief is livid that you took this story public before an internal investigation.",

  ["missions.organise_press_conference.title"] = "Organize Press Conference",
  ["missions.organise_press_conference.description"] = "Organize a press conference to publicly announce that you are about to identify and catch the Liberation Front's leadership.",
  ["missions.organise_press_conference.success"] = "The press is treating the announcement as an important piece of news, and spins it positively.",
  ["missions.organise_press_conference.fail"] = "The press did not seem to treat the announcement as credible.",

  ["missions.rumour_mongering.title"] = "Rumor Mongering",
  ["missions.rumour_mongering.description"] = "Let the information be leaked that you are about to identify and catch the Liberation Front's leadership.",
  ["missions.rumour_mongering.success"] = "The news seems to be spreading, from what we can tell, through the ranks of Liberation Front - slowly but surely.",
  ["missions.rumour_mongering.fail"] = "The news doesn't seem to be spreading, from what we can tell, through the ranks of the Liberation Front.",

  ["missions.city_hall_brief.title"] = "City Hall Brief",
  ["missions.city_hall_brief.description"] = "Brief Police Leadership and City Hall confidentially that you are about to identify and catch the Liberation Front's leadership.",
  ["missions.city_hall_brief.success"] = "We've been congratulated on our work, having yielded the most important outcome so soon.",
  ["missions.city_hall_brief.fail"] = "We've heard rumors that the brief is considered to lack credibility by those who reviewed it.",

  ["missions.brief_interpol.title"] = "Brief INTERPOL",
  ["missions.brief_interpol.description"] = "Keep INTERPOL abreast of the international angle and developments to do with the Liberation Front.",
  ["missions.brief_interpol.success"] = "We've received thanks from INTERPOL for our contribution and detailed briefing.",
  ["missions.brief_interpol.fail"] = "We've not been able to get the briefing on the desk of top INTERPOL decision-makers.",

  ["budget.wilson_donation.title"] = "Wilson Donation",
  ["budget.wilson_donation.description"] = "As requested by the incarcerated Daniel Wilson, finance the medical operation his mother requires as she is in critical condition and will not survive without immediate intervention.",

  ["press_release7.text1"] = "In order to ",
  ["press_release7.option_a1"] = "address public concerns",
  ["press_release7.option_a2"] = "ensure transparency",
  ["press_release7.text2"] = " regarding the police force's deployment of ",
  ["press_release7.option_b1"] = "several squads",
  ["press_release7.option_b2"] = "a few officers",
  ["press_release7.option_b3"] = "the ${squad_name} Special Unit",
  ["press_release7.text3"] = " at the KWM Plant, we are releasing this public statement.",
  ["press_release7.text4"] = "Following ",
  ["press_release7.option_c1"] = "an anonymous tip",
  ["press_release7.option_c2"] = "a request by a concerned employee",
  ["press_release7.option_c3"] = "common procedure",
  ["press_release7.text5"] = ", forces arrived at the scene in order to ",
  ["press_release7.option_d1"] = "assess if security standards were in order",
  ["press_release7.option_d2"] = "investigate a potential theft",
  ["press_release7.option_d3"] = "escort a transport convoy",
  ["press_release7.text6"] = ". When they arrived at the scene, officers found the factory empty, and Aaron King, the CEO, as well as Steve Muradian, Chief of Security, were contacted in order to clarify the situation. They explained that the factory was not operational that day, as the ",
  ["press_release7.option_e1"] = "employees were on vacation",
  ["press_release7.option_e2"] = "the production lines were under renovation",
  ["press_release7.text7"] = ". This clear case of miscommunication was quickly resolved, and the officers left the scene.",
  ["press_release7.text8"] = "We ask people to avoid any unfounded panic mongering and seek dialogue with the authorities for any further clarification. ",
  ["press_release7.option_f1"] = "Mister King is being questioned with regards to an unrelated investigation.",
  ["press_release7.option_f2"] = "Mister King has been arrested in relation to an unrelated investigation.",
  ["press_release7.option_f3"] = "Mister King is being held with suspicion of being a Liberation Front member.",

  ["press_release9.text1"] = "Today, while pursuing leads pertaining to our ongoing investigation into the Liberation Front, ${squad_name} Special Unit officers approached several individuals who we ",
  ["press_release9.option_a1"] = "believed to hold valuable information",
  ["press_release9.option_a2"] = "suspected of having ties with the terrorist organization",
  ["press_release9.option_a3"] = "knew to be connected to Liberation Front leadership",
  ["press_release9.text2"] = ". All of these individuals were scheduled to fly to Cambodia, and due to time constraints, our officers found it necessary to delay the flight in order to ",
  ["press_release9.option_b1"] = "consult",
  ["press_release9.option_b2"] = "arrest",
  ["press_release9.text3"] = " them. Airport authorities fully cooperated with our requests, and we were able to establish contact.",
  ["press_release9.text4"] = "Two of these people ",
  ["press_release9.option_c1"] = "agreed to come in for questioning",
  ["press_release9.option_c2"] = "were apprehended and questioned",
  ["press_release9.option_c3"] = "were taken by force given the urgency of the situation",
  ["press_release9.text5"] = ", and their input was very valuable. At this point, no official charges have yet been made against any of these individuals, but we continue to investigate the situation.",

  ["episode8.hint"] = "You are the subject of an interrogation. You need to:\n\n· Avoid giving out answers that directly incriminate you, and cause you to get suspended from your position with the task force.\n\n· Avoid raising the level of suspicion through your answers, to prevent being tortured for a confession.\n\n· Avoid angering your interrogator, to prevent being tortured for a confession.",
}
