-- luacheck: no max line length
return {
  ["cutscene.t1"] = "The evacuation started as soon as possible.\nWhen the bomb squad reached the device, we still had plenty of people to evacuate.",
  ["cutscene.t2"] = "We successfully disarmed the device in time, saving dozens of lives.",
  ["cutscene.t3"] = "Then the news started coming in from all around the city.",
  ["cutscene.t4"] = "Two other explosions happened close to the same time ours was set to.\nDozens of casualties.",


  ["missions.monitor_chatroom.title"] = "Focus on Chatroom Analysis",
  ["missions.monitor_chatroom.description"] = "Use all remaining available time on keeping the agent's eyes on the chatroom discussions. Gain and share an understanding of the people there and their objectives.",
  ["missions.monitor_chatroom.success"] = "We understand how they work better. Blackmailing/pressuring non-members is one of their methods, so we might want to inquire about that in the interrogations.",
  ["missions.monitor_chatroom.fail"] = "So much scrolling text, all apparently about cats. Hard to stay focused.",

  ["missions.pursue_advertisers.title"] = "Pursue Chatroom Advertisers",
  ["missions.pursue_advertisers.description"] = "Go to the people whose pet shops have advertisements for pet products and see if they have any information.",
  ["missions.pursue_advertisers.success"] = "We found them. But they seem to just be trying to sell their products. No discernible link to the Liberation Front.",
  ["missions.pursue_advertisers.fail"] = "We couldn't get a solid lead to the real people that placed the ads.",


  ["press_release1.text1"] = "The investigation involving the murder of Heather Peterson was concluded today, which resulted in the arrest of Darryl Peterson, 41, and Jerry Cox, 26. All evidence pertaining to the case has been directed to the relevant authorities, with the full cooperation and counsel of the STPD Prosecutor Councilor. ",
  ["press_release1.text2"] = " and their cases will be taken to criminal court.",
  ["press_release1.text3"] = "Darryl Peterson, ",
  ["press_release1.text4"] = ", confessed to the murder during questioning. Although he initially attempted to hide his involvement by staging a violent robbery, evidence found at the scene contradicted parts of his description of the event. The police will be advancing charges of ",
  ["press_release1.text5"] = ".",
  ["press_release1.text6"] = "Due to the confession, the manslaughter charges against Jerry Cox have been dropped, and he will only face prosecution for breaking and entering and theft. ",
  ["press_release1.option_a1"] = "They will be treated following judicial procedure",
  ["press_release1.option_a2"] = "The criminals have been incarcerated",
  ["press_release1.option_b1"] = "not initially a suspect",
  ["press_release1.option_b2"] = "the main suspect",
  ["press_release1.option_b3"] = "the victim's husband",
  ["press_release1.option_c1"] = "voluntary manslaughter",
  ["press_release1.option_c2"] = "first-degree murder",
  ["press_release1.option_d1"] = "His involvement in creating the circumstances for the murder to happen will be investigated further.",
  ["press_release1.option_d2"] = "Evidence suggests he had no violent intent and no connection to the murder.",

  ["press_release2.text1"] = "In response to ",
  ["press_release2.text2"] = " the STPD assembled the ",
  ["press_release2.text3"] = " special unit in order to counter this threat.",
  ["press_release2.text4"] = "An intelligence gathering operation of the respective unit has led to the interview and eventual arrest of Fred Ennis, a ",
  ["press_release2.text5"] = " of a terrorist cell. Two other suspects have been interviewed as part of the same investigation, but they have been released ",
  ["press_release2.text6"] = ".",
  ["press_release2.text7"] = "Along with his confession, Fred Ennis's interview also yielded ",
  ["press_release2.text8"] = ". The officers in charge of the investigation are hopeful that this information will be useful in preventing future terrorist attacks.",
  ["press_release2.option_a1"] = "the emergence of the terrorist organization that identifies itself as the \"Liberation Front\"",
  ["press_release2.option_a2"] = "the recent upsurge in terrorist activity",
  ["press_release2.option_c1"] = "confessed sympathizer",
  ["press_release2.option_c2"] = "suspected collaborator",
  ["press_release2.option_d1"] = "having proven their innocence",
  ["press_release2.option_d2"] = "due to a lack of evidence against them",
  ["press_release2.option_e1"] = "relevant information regarding the terrorist organization",
  ["press_release2.option_e2"] = "the password to a secure chat-room used by the terrorist organization",

  ["tutorial.exit_fail"] = "Too early for that, let's keep working him.",
  ["tutorial.exit_fail2"] = "We're getting closer, but let's keep working him.",
  ["tutorial.exit_fail3"] = "There's no need to revisit those, he's all set to respond to the <color=#ff1919>accusation question</color>!",
  ["tutorial.exit_success"] = "We've almost got him. We just have to press him the right way. There are ways in which you press an open subject and other ways in which you press a terrified subject like this one.",
  ["tutorial.step2_q1"] = "That just alienated him. Might be useful to intimidate, but now we're trying to build empathy.",
  ["tutorial.step2_q2"] = "That forced him even more on the defensive. Right now, we're looking to open him up...",
  ["tutorial.step2_q3_a1"] = "He's not buying it. <i>Yet.</i> Try opening up yourself when questioning the subject, then try this one again.",
  ["tutorial.step2_q3_a2"] = "There we go, we're getting there.",
  ["tutorial.step2_q4"] = "Okay, good, you seem more authentic. Now get closer to the subject.",
  ["tutorial.step3_q1_a1"] = "This isn't scaring him, he doesn't feel it could happen.",
  ["tutorial.step3_q2"] = "He doesn't seem scared by that. 'Might actually be clean.",
  ["tutorial.step3_q3"] = "So there are signs of fear, we're on to something.",
  ["tutorial.step3_q4_a1"] = "He's not buying it. <i>Yet.</i> Make him feel this is a real possibility, then ask him that again.",
  ["tutorial.step3_q4_a2"] = "Sometimes, the talks reveal <color=#ffff00>new information</color> that you can further pursue.",
  ["tutorial.step3_q5"] = "There we go, we're getting there. Now let's put him in a good place to negotiate.",
  ["tutorial.step4_q1"] = "He doesn't seem to empathize with that. You might need something harder.",
  ["tutorial.tutor1"] = "Welcome. This will be the first drill session of the <b>Investigative Interview and Interrogation Techniques</b> course.",
  ["tutorial.tutor2"] = "We'll be bringing in a subject. They're a trained actor, but should be fully in character for the duration of the interview. I'm considered invisible and inaudible by the actor, but I'll be guiding you along.",
  ["tutorial.tutor3"] = "Before any interrogation, the first thing to do is to consult the subject's file. This should give you vital insights into the case, helping you to identify what information or confession needs to be extracted.",
  ["tutorial.tutor4"] = "When you're done checking the files, you can bring in the subject. Be careful though - <b>now is not the case</b> - but when it will be a time-sensitive situation, this is when the clock starts ticking.",
  ["tutorial.tutor5"] = "So first things first, let's just try and <b>straight up ask him</b>. You can check the <color=#ff1919>accusation question</color> every now and then to get a sense of whether you're close to a confession.",
  ["tutorial.tutor6"] = "Right, so that <i>\"surprisingly\"</i> didn't work. We need to get the subject in the right state of mind to give us answers.",
  ["tutorial.tutor7"] = "So how do we do that? We have the following tools which we can use to see what state the subject is in:",
  ["tutorial.tutor8"] = "This shows us how open the subject is, by looking at pupil dilation corroborated with a few other signals. The wider the pupils are, the more open the subject is.",
  ["tutorial.tutor9"] = "This meter tells us how scared the subject is, by measuring pulse as well as other bodily symptoms. The quicker the heart rate, the more scared the subject is.",
  ["tutorial.tutor10"] = "Now you can influence these meters in all sorts of ways, from building a personal connection to exploiting their background, from cornering them in contradictions to roughing them up.",
  ["tutorial.tutor11"] = "Let's try to build a connection first.",
  ["tutorial.tutor12"] = "Be careful, some questions will alienate the subject instead of bringing them closer. Other questions will seem disingenuous if they're approached too suddenly. You'll probably want to start off as soft as possible.",
  ["tutorial.tutor13"] = "Okay, we have him opening up some. Good! That is why the meter now shows a wider circle than in the beginning.",
  ["tutorial.tutor14"] = "Now let's see how we could try to scare him. You want to intimidate, but don't jump to big threats right off the bat.",
  ["tutorial.tutor15"] = "Don't be afraid to ask a question more than once. Asking again with the subject in a different state or with new information on the table can yield new results.",
  ["tutorial.tutor16"] = "Okay, we've got him. As you can see, his pulse is much faster right now.",
  ["tutorial.tutor17"] = "Okay, now this is off the record, but I want you to know your... <i>options</i>.",
  ["tutorial.tutor18"] = "At any time you can stop the recorder tracking your questioning.",
  ["tutorial.tutor19"] = "This will make people suspicious. The public will ask what happened when the recording was stopped. You'll be accused, but ultimately it's your word against theirs. In a pinch, though... it's something to consider",
  ["tutorial.tutor20"] = "You have... means... of <i>\"enhanced interrogation\"</i> that can get a subject scared faster.",
  ["tutorial.tutor21"] = "Try a couple out. The actor will just pretend to be hurt.",
  ["tutorial.tutor22"] = "Doing this closes them off, but as you can see, now they're terrified. Beware that if you continue roughing them up, they might pass out. Start the recorder again when you're done.",
  ["tutorial.tutor23"] = "Sometimes, you'll be interrogating against the clock. When that's the case, keep your eyes on the timer.",
  ["tutorial.tutor24"] = "Sometimes, you'll be interrogating more than one guy. Switch between rooms, and be sure to cross-reference the info they give you.",
  ["tutorial.tutor25"] = "Anyway, you'll get to keep your manual after you finish the academy. It's great for refreshing your memory about what you learned today.",
  ["tutorial.tutor26"] = "Okay, now to wrap this up, we're ready to get a confession with the <color=#ff1919>accusation</color> question.",
  ["tutorial.tutor27"] = "Mission accomplished",

  ["outcome.win"] = "Interrogation Successful",
  ["outcome.lose"] = "Interrogation Failed",
  ["outcome.episode1.win"] = "With the confession secured, Darryl Peterson will be going to jail for a long time.\n\nWhat is this Liberation Front business, though?",
  ["outcome.episode2.win"] = "We're in! Now we can try to delicately draw out some information on the Liberation Front's plans.",
  ["outcome.episode2.lose"] = "We weren't able to log in on time, and we have no way of getting the new password.",
  ["outcome.episode3.lose"] = "You didn't find the bomb's location in time.",
}
