-- luacheck: no max line length
return {
  ["level_test_valerie.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_valerie.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_valerie.3"] = "They gasp for air, calling for help.",
  ["level_test_valerie.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_valerie.5"] = "Let's talk about something else.",
  ["level_test_valerie.6"] = "idle",
  ["level_test_valerie.7"] = "idle_scared",
  ["level_test_valerie.8"] = "idle_smile",
  ["level_test_valerie.9"] = "disgust",
  ["level_test_valerie.10"] = "scared",
  ["level_test_valerie.11"] = "smile",
  ["level_test_valerie.12"] = "smile",
  ["level_test_valerie.13"] = "nod",
  ["level_test_valerie.14"] = "nod",
  ["level_test_valerie.15"] = "double_nod",
  ["level_test_valerie.16"] = "wont_even",
  ["level_test_valerie.17"] = "terrified",
  ["level_test_valerie.18"] = "smug",
  ["level_test_valerie.19"] = "look_away",
  ["level_test_valerie.20"] = "headshake",
  ["level_test_valerie.21"] = "I have no idea what you're talking about.",
  ["level_test_valerie.22"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_valerie.23"] = "Ok.",
  ["level_test_valerie.24"] = "They nod.",
}
