-- luacheck: no max line length
return {
  ["level_test_lynda.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_lynda.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_lynda.3"] = "They gasp for air, calling for help.",
  ["level_test_lynda.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_lynda.5"] = "Let's talk about something else.",
  ["level_test_lynda.6"] = "idle_scared",
  ["level_test_lynda.7"] = "idle_empathy",
  ["level_test_lynda.8"] = "headshake",
  ["level_test_lynda.9"] = "disgust",
  ["level_test_lynda.10"] = "melancholy",
  ["level_test_lynda.11"] = "angry",
  ["level_test_lynda.12"] = "nod",
  ["level_test_lynda.13"] = "scared",
  ["level_test_lynda.14"] = "shrug",
  ["level_test_lynda.15"] = "smile",
  ["level_test_lynda.16"] = "snuggle",
  ["level_test_lynda.17"] = "terrified",
  ["level_test_lynda.18"] = "I have no idea what you're talking about.",
  ["level_test_lynda.19"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_lynda.20"] = "Ok.",
  ["level_test_lynda.21"] = "They nod.",
}
