-- luacheck: no max line length
return {
  ["level_test_fred.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_fred.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_fred.3"] = "They gasp for air, calling for help.",
  ["level_test_fred.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_fred.5"] = "Let's talk about something else.",
  ["level_test_fred.6"] = "fred_angry",
  ["level_test_fred.7"] = "fred_defense",
  ["level_test_fred.8"] = "fred_disgust",
  ["level_test_fred.9"] = "fred_guilty",
  ["level_test_fred.10"] = "fred_headshake",
  ["level_test_fred.11"] = "fred_nod",
  ["level_test_fred.12"] = "fred_scared",
  ["level_test_fred.13"] = "fred_shrug",
  ["level_test_fred.14"] = "fred_smile",
  ["level_test_fred.15"] = "fred_idle_scared",
  ["level_test_fred.16"] = "fred_quick_nod",
  ["level_test_fred.17"] = "fred_very_guilty",
  ["level_test_fred.18"] = "fred_exasperated",
  ["level_test_fred.19"] = "I have no idea what you're talking about.",
  ["level_test_fred.20"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_fred.21"] = "Ok.",
  ["level_test_fred.22"] = "They nod.",
}
