-- luacheck: no max line length
return {
  ["level_test_dennis.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_dennis.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_dennis.3"] = "They gasp for air, calling for help.",
  ["level_test_dennis.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_dennis.5"] = "Let's talk about something else.",
  ["level_test_dennis.6"] = "idle",
  ["level_test_dennis.7"] = "idle_scared",
  ["level_test_dennis.8"] = "idle_empathy",
  ["level_test_dennis.9"] = "angry",
  ["level_test_dennis.10"] = "nod",
  ["level_test_dennis.11"] = "bored",
  ["level_test_dennis.12"] = "disgusted",
  ["level_test_dennis.13"] = "shrug",
  ["level_test_dennis.14"] = "smile",
  ["level_test_dennis.15"] = "terrified",
  ["level_test_dennis.16"] = "what",
  ["level_test_dennis.17"] = "scared",
  ["level_test_dennis.18"] = "headshake",
  ["level_test_dennis.19"] = "I have no idea what you're talking about.",
  ["level_test_dennis.20"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_dennis.21"] = "Ok.",
  ["level_test_dennis.22"] = "They nod.",
}
