-- luacheck: no max line length
return {
  ["level_test_adams.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_adams.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_adams.3"] = "They gasp for air, calling for help.",
  ["level_test_adams.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_adams.5"] = "Let's talk about something else.",
  ["level_test_adams.6"] = "Double Nod",
  ["level_test_adams.7"] = "Headshake",
  ["level_test_adams.8"] = "Idle",
  ["level_test_adams.9"] = "Idle Empathy",
  ["level_test_adams.10"] = "Nod",
  ["level_test_adams.11"] = "Nod Smile",
  ["level_test_adams.12"] = "Pray",
  ["level_test_adams.13"] = "Really",
  ["level_test_adams.14"] = "Scared",
  ["level_test_adams.15"] = "Shrug",
  ["level_test_adams.16"] = "Sigh",
  ["level_test_adams.17"] = "Sigh Smile",
  ["level_test_adams.18"] = "Smile",
  ["level_test_adams.19"] = "Terrified",
  ["level_test_adams.20"] = "I have no idea what you're talking about.",
  ["level_test_adams.21"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_adams.22"] = "Ok.",
  ["level_test_adams.23"] = "They nod.",
}
