-- luacheck: no max line length
return {
  ["level_test_helene.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_helene.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_helene.3"] = "They gasp for air, calling for help.",
  ["level_test_helene.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_helene.5"] = "Let's talk about something else.",
  ["level_test_helene.6"] = "terrified",
  ["level_test_helene.7"] = "nod",
  ["level_test_helene.8"] = "yoga_pose",
  ["level_test_helene.9"] = "headshake",
  ["level_test_helene.10"] = "shrug",
  ["level_test_helene.11"] = "disgust",
  ["level_test_helene.12"] = "shrug_sign",
  ["level_test_helene.13"] = "shrug_plus_sign",
  ["level_test_helene.14"] = "of",
  ["level_test_helene.15"] = "upset",
  ["level_test_helene.16"] = "sad",
  ["level_test_helene.17"] = "smile",
  ["level_test_helene.18"] = "headshake_sign",
  ["level_test_helene.19"] = "headshake_plus_sign",
  ["level_test_helene.20"] = "I have no idea what you're talking about.",
  ["level_test_helene.21"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_helene.22"] = "Ok.",
  ["level_test_helene.23"] = "They nod.",
  ["level_test_helene.24"] = "Y U Do these ridiculous thing is disgusting like hell",
  ["level_test_helene.25"] = "Hahaha",
}
