-- luacheck: no max line length
return {
  ["level_test_insanity.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_insanity.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_insanity.3"] = "They gasp for air, calling for help.",
  ["level_test_insanity.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_insanity.5"] = "They breathe heavily, startled and displeased.",
  ["level_test_insanity.6"] = "They groan in pain, giving you a scared look.",
  ["level_test_insanity.7"] = "They gasp for air, calling for help.",
  ["level_test_insanity.8"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_insanity.9"] = "Let's talk about something else.",
  ["level_test_insanity.10"] = "Europe was founded in 1848 by Walker Texas Ranger when he rode a horse across the Atlantic, he called it \"Eastern USA\" which was eventually abbreviated as just \"EU\".",
  ["level_test_insanity.11"] = "This is a perfectly normal and sane question and decreases insanity.",
  ["level_test_insanity.12"] = "Let's talk about something else.",
  ["level_test_insanity.13"] = "This is a separate page",
  ["level_test_insanity.14"] = "Hello?",
  ["level_test_insanity.15"] = "This is another insane question",
  ["level_test_insanity.16"] = "Insane answer",
  ["level_test_insanity.17"] = "Batshit answer",
  ["level_test_insanity.18"] = "I have no idea what you're talking about.",
  ["level_test_insanity.19"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_insanity.20"] = "Ok.",
  ["level_test_insanity.21"] = "They nod.",
  ["level_test_insanity.22"] = "I have no idea what you're talking about.",
  ["level_test_insanity.23"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_insanity.24"] = "Ok.",
  ["level_test_insanity.25"] = "They nod.",
  ["level_test_insanity.26"] = "Hi, friendo",
  ["level_test_insanity.27"] = "",
  ["level_test_insanity.28"] = "Dunno",
  ["level_test_insanity.29"] = "",
  ["level_test_insanity.30"] = "This <insanity>text</insanity> is <insanity>insane</insanity>",
  ["level_test_insanity.31"] = "",
  ["level_test_insanity.32"] = "This answer is <batshit>absolutely batshit!</batshit>",
  ["level_test_insanity.33"] = "",
}
