-- luacheck: no max line length
return {
  ["level_episode0.1"] = "They breathe heavily - startled and displeased.",
  ["level_episode0.2"] = "They groan in pain, giving you a scared look.",
  ["level_episode0.3"] = "They gasp for air, calling for help.",
  ["level_episode0.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_episode0.5"] = "So, why do you steal bikes, Douglas?",
  ["level_episode0.6"] = "Says in your file your folks are loaded. What's the matter, they cut you off?",
  ["level_episode0.7"] = "Says in your file your folks are loaded. You steal for fun?",
  ["level_episode0.8"] = "Hey, living's expensive, I know. I use to crack payphones when I was a teen'.",
  ["level_episode0.9"] = "Can't believe they have me chasing bikes. Why can't people just lock'em up proper?",
  ["level_episode0.10"] = "Look, you'll be fine, we'll help you compensate the victims, make things right. Ready to sign a confession?",
  ["level_episode0.11"] = "Listen you lowlife, sign this damn confession right now and maybe we can keep your dumb ass out of jail!",
  ["level_episode0.12"] = "If we don't have a deal, and you're found guilty, it's absolutely prison time. But I can only give you a deal if you plead guilty.",
  ["level_episode0.13"] = "Did the drugs make you do it?",
  ["level_episode0.14"] = "You know how many months you do for bike theft?",
  ["level_episode0.15"] = "Hey, you're tough, you'll be fine in prison, I'm sure.",
  ["level_episode0.16"] = "Let's talk about you writing a confession. We both know you did it, come on...",
  ["level_episode0.17"] = "Let's talk about you writing a confession. We both know you did it, come on...",
  ["level_episode0.18"] = "Let's talk about you writing a confession. We both know you did it, come on...",
  ["level_episode0.19"] = "Oh? You think this senator will risk his career for the sake of a bike-snatchin' kid? Really?",
  ["level_episode0.20"] = "I have no idea what you're talking about.",
  ["level_episode0.21"] = "They look into your eyes, perhaps a bit worried.",
  ["level_episode0.22"] = "Ok.",
  ["level_episode0.23"] = "They nod.",
  ["level_episode0.24"] = "Huh? I ain't steal no bikes, brosef.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.25"] = "They say with a smirk.",
  ["level_episode0.26"] = "That ain't none of your business man.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.27"] = "They act outraged.",
  ["level_episode0.28"] = "Fuck you man, no.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.29"] = "They state slowly.",
  ["level_episode0.30"] = "Psh, fuckin' doubt it.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.31"] = "They shake their head in disbelief.",
  ["level_episode0.32"] = "Word? That's thug.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.33"] = "They say with a tinge of disbelief.",
  ["level_episode0.34"] = "It's fuckin' stupid man. Waste a' taxpayer money and all that.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.35"] = "They seem amused.",
  ["level_episode0.36"] = "N-naw, naw. Wasn't me, man. Naw.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.37"] = "Their voice is cracking.",
  ["level_episode0.38"] = "Fuck man, fuck. Shit, okay. Okay. Allright, I'll sign.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.39"] = "They say in despair.",
  ["level_episode0.40"] = "I don't need no deal, pig. I'm innocent!<nobr> <img=t:advance/></nobr>",
  ["level_episode0.41"] = "They spit out the words.",
  ["level_episode0.42"] = "But like... I mean... What would a deal be like?<nobr> <img=t:advance/></nobr>",
  ["level_episode0.43"] = "They seem concerned.",
  ["level_episode0.44"] = "I'm clean, yo.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.45"] = "They say with confidence.",
  ["level_episode0.46"] = "N-naw man, naw. I ain't worried 'bout that.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.47"] = "They state timidly.",
  ["level_episode0.48"] = "I'd be just fine inside yo.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.49"] = "They say with bravado.",
  ["level_episode0.50"] = "W-what? You don't do time for snatchin' bikes... Do you? M-my dad works for a s-senator. I'll be fine.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.51"] = "They avoid your gaze.",
  ["level_episode0.52"] = "We don't know nothin', I'm not signin' nothin', naw.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.53"] = "They look at you in disbelief.",
  ["level_episode0.54"] = "Wha'? Naw, naw... Erm, what would, like, that involve though?<nobr> <img=t:advance/></nobr>",
  ["level_episode0.55"] = "They seem concerned.",
  ["level_episode0.56"] = "We don't know nothin', I'm not signin' nothin', naw.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.57"] = "They look at you in disbelief.",
  ["level_episode0.58"] = "We don't know nothin', I'm not signin' nothin', naw.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.59"] = "They look at you in disbelief.",
  ["level_episode0.60"] = "Wha'? Naw, naw... Erm, what would, like, that involve though?<nobr> <img=t:advance/></nobr>",
  ["level_episode0.61"] = "They seem concerned.",
  ["level_episode0.62"] = "P-probably not. Shit. Shit.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.63"] = "They shift in their seat in distress.",
  ["level_episode0.64"] = "I- uh. Naw, naw. Only fools confess. I ain't do it.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.65"] = "They shake their head.",
  ["level_episode0.66"] = "I- uh. Naw, naw. Only fools confess. I ain't do it.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.67"] = "They shake their head.",
  ["level_episode0.68"] = "I- uh. Naw, naw. Only fools confess. I ain't do it.<nobr> <img=t:advance/></nobr>",
  ["level_episode0.69"] = "They shake their head.",
  ["level_episode0.70"] = "",
  ["level_episode0.71"] = "",
  ["level_episode0.72"] = "",
  ["level_episode0.73"] = "",
  ["level_episode0.74"] = "",
  ["level_episode0.75"] = "",
  ["level_episode0.76"] = "",
  ["level_episode0.77"] = "",
  ["level_episode0.78"] = "",
  ["level_episode0.79"] = "",
}
