-- luacheck: no max line length
return {
  ["level_test_daniel.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_daniel.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_daniel.3"] = "They gasp for air, calling for help.",
  ["level_test_daniel.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_daniel.5"] = "Let's talk about something else.",
  ["level_test_daniel.6"] = "This is makes Daniel nod",
  ["level_test_daniel.7"] = "This makes Daniel shake his head",
  ["level_test_daniel.8"] = "This makes Daniel sad",
  ["level_test_daniel.9"] = "This makes Daniel shrug",
  ["level_test_daniel.10"] = "Smile",
  ["level_test_daniel.11"] = "Terrified",
  ["level_test_daniel.12"] = "Upset",
  ["level_test_daniel.13"] = "I have no idea what you're talking about.",
  ["level_test_daniel.14"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_daniel.15"] = "Ok.",
  ["level_test_daniel.16"] = "They nod.",
  ["level_test_daniel.17"] = "Yes, it does.",
  ["level_test_daniel.18"] = "They state resolutely",
  ["level_test_daniel.19"] = "Nope, it doesn't",
  ["level_test_daniel.20"] = "They state with a slight curl to the corner of their lips",
  ["level_test_daniel.21"] = "Life sucks",
  ["level_test_daniel.22"] = "They state on a low volume",
  ["level_test_daniel.23"] = "I don't know, does it?",
  ["level_test_daniel.24"] = "They seem amused.",
}
