-- luacheck: no max line length
return {
  ["level_test_reed.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_reed.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_reed.3"] = "They gasp for air, calling for help.",
  ["level_test_reed.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_reed.5"] = "Let's talk about something else.",
  ["level_test_reed.6"] = "idle",
  ["level_test_reed.7"] = "Cross Arms",
  ["level_test_reed.8"] = "Make a deal",
  ["level_test_reed.9"] = "Disgusting like hell",
  ["level_test_reed.10"] = "Headshake",
  ["level_test_reed.11"] = "Nod",
  ["level_test_reed.12"] = "No Problem",
  ["level_test_reed.13"] = "Not Me",
  ["level_test_reed.14"] = "Really",
  ["level_test_reed.15"] = "Remorse",
  ["level_test_reed.16"] = "Shrug",
  ["level_test_reed.17"] = "Shrug Disgust",
  ["level_test_reed.18"] = "Smile",
  ["level_test_reed.19"] = "Terrified",
  ["level_test_reed.20"] = "What",
  ["level_test_reed.21"] = "I have no idea what you're talking about.",
  ["level_test_reed.22"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_reed.23"] = "Ok.",
  ["level_test_reed.24"] = "They nod.",
}
