local fui = require("main.fuior.runtime")
local compiler = require("main.fuior.compiler")
local scenes = require("main.progression.scenes")
local func = function ()
	return function (fui)
		local intl = fui.intl(nil)

		fui.load_interlude("office_floor")
		fui.load_characters("jen", "tab", "mordecai")
		fui.wait(2)
		fui.show_character("jen", "LEFT")
		fui.show_character("tab", "RIGHT_CENTER")
		fui.show_character("mordecai", "RIGHT")
		fui.wait(1)
		fui.text("jen", "pointing", intl("80035d.interlude_d2.1c4384"))
		fui.text("jen", "explain_angry", intl("80035d.interlude_d2.2cf15f"))
		fui.text("mordecai", "hips", intl("80035d.interlude_d2.654890"))
		fui.animate("jen", "normal")
		fui.text("mordecai", "explain", intl("80035d.interlude_d2.27058a"))
		fui.text("tab", "defensive", intl("80035d.interlude_d2.3d8ade"))
		fui.animate("mordecai", "normal")
		fui.text("tab", "defensive", intl("80035d.interlude_d2.cfcf8d"))
		fui.wait_for_input()
		fui.hide_all_characters()
	end
end()

return scenes.skippable(function ()
	func(fui.new())
end)
