local fui = require("main.fuior.runtime")
local compiler = require("main.fuior.compiler")
local scenes = require("main.progression.scenes")
local func = function ()
	return function (fui)
		local intl = fui.intl(nil)

		fui.load_interlude("office_floor")
		fui.load_characters("mordecai")
		fui.wait(2)
		fui.show_character("mordecai", "RIGHT")
		fui.wait(1)
		fui.text("mordecai", "thinking", intl("80035d.interlude_d3.e1553d"))
		fui.text("mordecai", "proud", intl("80035d.interlude_d3.b71330"))
		fui.text("mordecai", "proud", intl("80035d.interlude_d3.9ea852"))
		fui.text("mordecai", "normal", intl("80035d.interlude_d3.bd6bf3"))
		fui.text("mordecai", "thinking", intl("80035d.interlude_d3.971e95"))
		fui.text("mordecai", "point", intl("80035d.interlude_d3.0f59c7"))
		fui.text("mordecai", "point", intl("80035d.interlude_d3.12de06"))
		fui.wait_for_input()
		fui.hide_all_characters()
	end
end()

return scenes.skippable(function ()
	func(fui.new())
end)
