local fui = require("main.fuior.runtime")
local compiler = require("main.fuior.compiler")
local scenes = require("main.progression.scenes")
local func = function ()
	return function (fui)
		local intl = fui.intl(nil)

		fui.load_interlude("office_floor")
		fui.load_characters("jen", "tab", "mordecai")
		fui.wait(2)
		fui.show_character("jen", "LEFT")
		fui.show_character("tab", "RIGHT_CENTER")
		fui.show_character("mordecai", "RIGHT")
		fui.wait(1)
		fui.text("jen", "explain", intl("80035d.interlude_d4.fb6568"))
		fui.text("mordecai", "gun", intl("80035d.interlude_d4.416a3b"))
		fui.animate("jen", "normal")
		fui.text("tab", "defensive", intl("80035d.interlude_d4.a36671"))
		fui.text("tab", "listening", intl("80035d.interlude_d4.03b041"))
		fui.animate("mordecai", "normal")
		fui.wait_for_input()
		fui.hide_all_characters()
	end
end()

return scenes.skippable(function ()
	func(fui.new())
end)
