-- luacheck: no max line length
return {
  ["level_test_interpreter.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_interpreter.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_interpreter.3"] = "They gasp for air, calling for help.",
  ["level_test_interpreter.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_interpreter.5"] = "They breathe heavily, startled and displeased.",
  ["level_test_interpreter.6"] = "They groan in pain, giving you a scared look.",
  ["level_test_interpreter.7"] = "They gasp for air, calling for help.",
  ["level_test_interpreter.8"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_interpreter.9"] = "Let's talk about something else.",
  ["level_test_interpreter.10"] = "Let's talk about something else.",
  ["level_test_interpreter.11"] = "No interpreter animation",
  ["level_test_interpreter.12"] = "This animates the interpreter character",
  ["level_test_interpreter.13"] = "The fact that so many books still name the Beatles as \"the greatest or most significant or most influential\" rock band ever only tells you how far rock music still is from becoming a serious art.",
  ["level_test_interpreter.14"] = "Jazz critics have long recognized that the greatest jazz musicians of all times are Duke Ellington and John Coltrane, who were not the most famous or richest or best sellers of their times, let alone of all times.",
  ["level_test_interpreter.15"] = "This animates the regular character",
  ["level_test_interpreter.16"] = "I have no idea what you're talking about.",
  ["level_test_interpreter.17"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_interpreter.18"] = "Ok.",
  ["level_test_interpreter.19"] = "They nod.",
  ["level_test_interpreter.20"] = "I have no idea what you're talking about.",
  ["level_test_interpreter.21"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_interpreter.22"] = "Ok.",
  ["level_test_interpreter.23"] = "They nod.",
  ["level_test_interpreter.24"] = "I am not animating",
  ["level_test_interpreter.25"] = "Memes",
  ["level_test_interpreter.26"] = "I am now animating",
  ["level_test_interpreter.27"] = "More memes",
  ["level_test_interpreter.28"] = "Scaruffi sucks dude, stop.",
  ["level_test_interpreter.29"] = "They raise their eyebrow",
  ["level_test_interpreter.30"] = "Classical critics rank the highly controversial Beethoven over classical musicians who were highly popular in courts around Europe. Rock critics are still blinded by commercial success.",
  ["level_test_interpreter.31"] = "Thinks about progressive jazzcore",
  ["level_test_interpreter.32"] = "This deaf mute char is now animating",
  ["level_test_interpreter.33"] = "",
}
