-- luacheck: no max line length
return {
  ["level_test_alex.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_alex.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_alex.3"] = "They gasp for air, calling for help.",
  ["level_test_alex.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_alex.5"] = "Let's talk about something else.",
  ["level_test_alex.6"] = "Transition to crazy",
  ["level_test_alex.7"] = "Transition to normal",
  ["level_test_alex.8"] = "smile_crazy",
  ["level_test_alex.9"] = "nod_crazy",
  ["level_test_alex.10"] = "headshake_crazy",
  ["level_test_alex.11"] = "multi_nod_crazy",
  ["level_test_alex.12"] = "look_away_crazy",
  ["level_test_alex.13"] = "multi_nod",
  ["level_test_alex.14"] = "shrug",
  ["level_test_alex.15"] = "smile",
  ["level_test_alex.16"] = "disgust",
  ["level_test_alex.17"] = "headshake",
  ["level_test_alex.18"] = "angry",
  ["level_test_alex.19"] = "nod",
  ["level_test_alex.20"] = "nod_long",
  ["level_test_alex.21"] = "look_away",
  ["level_test_alex.22"] = "I have no idea what you're talking about.",
  ["level_test_alex.23"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_alex.24"] = "Ok.",
  ["level_test_alex.25"] = "They nod.",
}
