-- luacheck: no max line length
return {
  ["level_test_tab.1"] = "They breathe heavily, startled and displeased.",
  ["level_test_tab.2"] = "They groan in pain, giving you a scared look.",
  ["level_test_tab.3"] = "They gasp for air, calling for help.",
  ["level_test_tab.4"] = "They yell out in pain, insisting that they are innocent.",
  ["level_test_tab.5"] = "Let's talk about something else.",
  ["level_test_tab.6"] = "cross_arms",
  ["level_test_tab.7"] = "explain",
  ["level_test_tab.8"] = "disgust",
  ["level_test_tab.9"] = "headshake",
  ["level_test_tab.10"] = "sigh",
  ["level_test_tab.11"] = "nod",
  ["level_test_tab.12"] = "double_nod",
  ["level_test_tab.13"] = "shrug",
  ["level_test_tab.14"] = "smile",
  ["level_test_tab.15"] = "terrified",
  ["level_test_tab.16"] = "cross_arms",
  ["level_test_tab.17"] = "cross_arms",
  ["level_test_tab.18"] = "I have no idea what you're talking about.",
  ["level_test_tab.19"] = "They look into your eyes, perhaps a bit worried.",
  ["level_test_tab.20"] = "Ok.",
  ["level_test_tab.21"] = "They nod.",
}
