local fui = require("main.fuior.runtime")
local compiler = require("main.fuior.compiler")
local scenes = require("main.progression.scenes")
local func = function ()
	return function (fui)
		local intl = fui.intl(nil)

		fui.load_interlude("chief_office")
		fui.load_characters("dummy")
		fui.show_character("dummy", "CHIEF", false, "chief")
		fui.wait(2)
		fui.text("dummy", nil, intl("81039c.interlude_g3.2725df"))
		fui.text("dummy", nil, intl("81039c.interlude_g3.fb7a06"))
		fui.text("dummy", nil, intl("81039c.interlude_g3.483749"))
		fui.text("dummy", nil, intl("81039c.interlude_g3.bb3991"))
		fui.wait_for_input()
		fui.hide_all_characters()
	end
end()

return scenes.skippable(function ()
	func(fui.new())
end)
