local fui = require("main.fuior.runtime")
local compiler = require("main.fuior.compiler")
local scenes = require("main.progression.scenes")
local func = function ()
	return function (fui)
		local intl = fui.intl(nil)

		fui.set_preset_music("campaign")
		fui.load_interlude("chief_office")
		fui.load_characters("dummy")
		fui.show_character("dummy", "CHIEF", false, "chief")
		fui.wait(2)
		fui.text("dummy", nil, intl("efd00d.triggered_warning_popularity.b4a680"))
		fui.text("dummy", nil, intl("efd00d.triggered_warning_popularity.dd2f07"))
		fui.text("dummy", nil, intl("efd00d.triggered_warning_popularity.c49e49"))
		fui.text("dummy", nil, intl("efd00d.triggered_warning_popularity.a6ad2a"))
		fui.wait_for_input()
		fui.hide_all_characters()
	end
end()

return scenes.skippable(function ()
	func(fui.new())
end)
